# Generated by Django 5.1.3 on 2024-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=600)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('publish_date', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
